mysql:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3308/tsgzdbnew?autoReconnect=true&&useTimezone=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=true&allowMultiQueries=true
    #    username: tsgzuser
    #    password: tsgzpassword
    username: root
    password: root

clickhouse:
  datasource:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    jdbc-url: jdbc:clickhouse://47.111.79.98:8088/test_cjy?socket_timeout=300000
    password:
    initialSize: 10
    maxActive: 100
    minIdle: 10
    maxWait: 6000

spring:
  kafka:
    bootstrap-servers: 45.77.209.211:9092 #服务器的ip及端口，可以写多个，服务器之间用“：”间隔
    producer: #生产者配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer: #消费者配置
      group-id: branch-event #设置消费者的组id
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka-topic:
  security-add: branch-event
  origin-alarm-log: branch-orglog
  security-update: branch-process

