mysql:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://10.209.67.100:3306/tsgzdbnew?autoReconnect=true&&useTimezone=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=true&allowMultiQueries=true
    #    username: tsgzuser
    #    password: tsgzpassword
    username: tsadmin
    password: Xybc@12#$

clickhouse:
  datasource:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    jdbc-url: jdbc:clickhouse://10.209.67.95:8123/rtc
    password:
    initialSize: 10
    maxActive: 100
    minIdle: 10
    maxWait: 6000

spring:
  kafka:
    bootstrap-servers: 10.243.103.56:29092,10.243.103.59:29092,10.243.103.60:29092,10.243.103.72:29092,10.243.103.73:29092,10.243.103.74:29092 #服务器的ip及端口，可以写多个，服务器之间用“：”间隔
    producer: #生产者配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer: #消费者配置
      group-id: branch-event #设置消费者的组id
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka-topic:
  security-add: branch-event
  origin-alarm-log: branch-orglog
  security-update: branch-process
